dae_project_2017/dae_project_2017-war/src/java/web/ManageBeans/ProponenteManagedBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package web.ManageBeans;

import dtos.InstituicaoDTO;
import dtos.ProfessorDTO;
import dtos.ProponenteDTO;
import dtos.PropostaDTO;
import dtos.SupervisorDTO;
import ejbs.ConfigBean;
import ejbs.InstituicaoBean;
import ejbs.ProfessorBean;
import ejbs.ProponenteBean;
import ejbs.PropostaBean;
import ejbs.SupervisorBean;
import java.util.logging.Logger;
import web.FacesExceptionHandler;
import java.io.Serializable;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.component.UIParameter;
import javax.faces.event.ActionEvent;
import javax.ws.rs.client.Entity;
import javax.ws.rs.core.GenericType;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import util.URILookup;
import utils.TipoTrabalho;

/**
 *
 * @author vsc
 */
@ManagedBean
@SessionScoped
public class ProponenteManagedBean extends UserManagedBean<ProponenteDTO> implements Serializable {

    private UIComponent component;
    private Response response;
    private SupervisorDTO newSupervisor;
    private PropostaDTO currentProposta;
    private PropostaDTO newProposta;

    // #######################################################################
    public ProponenteManagedBean() {
        super(ProponenteDTO.class);
        this.logger = Logger.getLogger("web.ProponenteManagedBean");
        newSupervisor = new SupervisorDTO();
        currentProposta = new PropostaDTO();
        newProposta = new PropostaDTO();
    }
    
    // #######################################################################
    @Override
    protected String getRestPathToFindUser(String username) {
        return ProponenteBean.REST_PATH_GET_FIND(username);
    }

    // #######################################################################
    public Collection<PropostaDTO> getAllPropostasDoProponenteLoggado() {
        response = client.target(URILookup.getBaseAPI())
                    .path(ProponenteBean.REST_PATH_GET_PROPOSTAS(loginManagedBean.getUsername()))
                    .request(MediaType.APPLICATION_XML)
                    .get();
            
        if (response.getStatusInfo().getFamily() != Response.Status.Family.SUCCESSFUL) {
            FacesExceptionHandler.handleException(
                    response,
                    "Erro ao carregar as propostas do proponente loggado!",
                    component,
                    logger
            );

        }
        List<PropostaDTO> dtos = response.readEntity(new GenericType<List<PropostaDTO>>() {});
        return dtos;
    }
    
    public String createProposta() {
        newProposta.setMestrado(ConfigBean.MESTRADO);
        
        newProposta.removeProponenteUsername(loginManagedBean.getUsername());
        
        newProposta.addProponenteUsername(loginManagedBean.getUsername());
        newProposta.setConcursoId(loginManagedBean.getLatestConcurso().getId());
        
        
        response = client.target(URILookup.getBaseAPI())
                .path(PropostaBean.REST_PATH_CREATE)
                .request(MediaType.APPLICATION_XML)
                .post(Entity.xml(newProposta));

        if (response.getStatusInfo().getFamily() != Response.Status.Family.SUCCESSFUL) {
            FacesExceptionHandler.handleException(
                    response, "Erro ao tentar criar a proposta", 
                    component, logger);
            return null;
        }
        
        newProposta.reset();
        return "proponente_index?faces-redirect=true";
    }

    
    public String updateProposta() {
        currentProposta.setMestrado(ConfigBean.MESTRADO);
        
        currentProposta.removeProponenteUsername(loginManagedBean.getUsername());
        currentProposta.addProponenteUsername(loginManagedBean.getUsername());
        currentProposta.setConcursoId(loginManagedBean.getLatestConcurso().getId());
        
        response = client.target(URILookup.getBaseAPI())
                .path(PropostaBean.REST_PATH_UPDATE)
                .request(MediaType.APPLICATION_XML)
                .put(Entity.xml(currentProposta));

        if (response.getStatusInfo().getFamily() != Response.Status.Family.SUCCESSFUL) {
            FacesExceptionHandler.handleException(
                    response, 
                    "Erro ao tentar atualizar a proposta!", 
                    component, logger);
            return null;
        }
        currentProposta.reset();
        return "proponente_index?faces-redirect=true";
    }
    
    public void removeProposta(ActionEvent event) {
        UIParameter param 
                = (UIParameter) event.getComponent().findComponent("propostaId");
        //propostaBean.remove((Long) param.getValue());
        String id = param.getValue().toString();

        response = client.target(URILookup.getBaseAPI())
                .path(PropostaBean.REST_PATH_DELETE(id))
                .request(MediaType.APPLICATION_XML)
                .delete();

        if (response.getStatusInfo().getFamily() != Response.Status.Family.SUCCESSFUL) {
            FacesExceptionHandler.handleException(
                    response,
                    "Erro ao tentar remover a proposta",
                    component, logger);
        }
    }
    
    public List<TipoTrabalho> getAllTiposDeTrabalho() {
        try {
            return Arrays.asList(TipoTrabalho.values());
        } catch (Exception e) {
            FacesExceptionHandler.handleException(
                    e,
                    "Erro ao carregar os tipos de trabalho!",
                   component,  logger
            );
            return null;
        }
    }
    
    /*##################################################################
                                                            PROFESSORES
    #####################################################################*/
    
    public Collection<ProfessorDTO> getAllProfessores() {
        response = client.target(URILookup.getBaseAPI())
                .path(ProfessorBean.REST_PATH_GET_ALL)
                .request(MediaType.APPLICATION_XML)
                .get();

        if (response.getStatusInfo().getFamily() != Response.Status.Family.SUCCESSFUL) {
            FacesExceptionHandler.handleException(
                    response,
                    "Erro ao carregar todos os professores!",
                    component, logger
            );
        }
        return response.readEntity(new GenericType<List<ProfessorDTO>>() {});
    }
      /*##################################################################
                                                            SUPERVISORES
    #####################################################################*/
    public boolean isInstituicao(){
        try {
             InstituicaoDTO instDTO = client.target(URILookup.getBaseAPI())
                    .path(InstituicaoBean.REST_PATH_GET_FIND(loginManagedBean.getUsername()))
                    .request(MediaType.APPLICATION_XML)
                    .get(InstituicaoDTO.class);
             return instDTO != null;
        } catch (Exception e) {
            return false;
        }
    }
    
    public Collection<SupervisorDTO> getAllSupervisorsOfInstituicao(){
        response = client.target(URILookup.getBaseAPI())
                .path(SupervisorBean.REST_PATH_GET_ALL_DE_INSTITUICAO(loginManagedBean.getUsername()))
                .request(MediaType.APPLICATION_XML)
                .get();
        if (response.getStatusInfo().getFamily() != Response.Status.Family.SUCCESSFUL) {
            FacesExceptionHandler.handleException(
                    response,
                    "Erro ao carregar os supervisores da instituicao",
                    component, logger
            );
        }
        return response.readEntity(new GenericType<List<SupervisorDTO>>() {});
    } 
    
    public String createSupervisor() {
        newSupervisor.setInstituicaoUsername(loginManagedBean.getUsername());
        response = client.target(URILookup.getBaseAPI())
                .path(SupervisorBean.REST_PATH_PUT_CREATE)
                .request(MediaType.APPLICATION_XML)
                .put(Entity.xml(newSupervisor));

        if (response.getStatusInfo().getFamily() != Response.Status.Family.SUCCESSFUL) {
            FacesExceptionHandler.handleException(
                    response,
                    "Erro ao criar supervisor!",
                    component, logger
            );
            return null; // todo erros nao aparecem : e.g. username ja existe ou mail 
        }
        
        newSupervisor.reset();
        return "proponente_index?faces-redirect=true";
    }
    
    public UIComponent getComponent() {
        return component;
    }

    public void setComponent(UIComponent component) {
        this.component = component;
    }

    public PropostaDTO getCurrentProposta() {
        return currentProposta;
    }

    public void setCurrentProposta(PropostaDTO currentProposta) {
        this.currentProposta = currentProposta;
    }

    public PropostaDTO getNewProposta() {
        return newProposta;
    }

    public void setNewProposta(PropostaDTO newProposta) {
        this.newProposta = newProposta;
    }

    public SupervisorDTO getNewSupervisor() {
        return newSupervisor;
    }

    public void setNewSupervisor(SupervisorDTO newSupervisor) {
        this.newSupervisor = newSupervisor;
    }
    
    
}

dae_project_2017/dae_project_2017-war/web/resources/emcomp/add_string_list.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" 
      xmlns:h="http://xmlns.jcp.org/jsf/html"  
      xmlns:composite="http://xmlns.jcp.org/jsf/composite">    

    <composite:interface> 
        <composite:attribute name="list" required="true"/> 
        <composite:attribute name="actionAdd" required="true"/> 
    </composite:interface>

    <composite:implementation>   

        <h:inputText binding="#{inut}" id="${cc.attrs.id_tag}" value="${cc.attrs.value}" />
        <h:commandButton
                    value="Adicinonar"
                    class="btn btn-info" 
                    action="${cc.attrs.actionAdd}" />

    </composite:implementation> 

</html> 

dae_project_2017/dae_project_2017-war/web/resources/emcomp/dt.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" 
      xmlns:h="http://xmlns.jcp.org/jsf/html" 
      xmlns:p="http://primefaces.org/ui" 
      xmlns:composite="http://xmlns.jcp.org/jsf/composite"   
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"    
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      >    
    
    <composite:interface>    
        <composite:attribute name="title" required="false"/>    
        <composite:attribute name="headers" required="true"/>      
        <composite:attribute name="list" required="true"/> 
        <composite:attribute name="props" required="true"/>
    </composite:interface>    
    
    <composite:implementation>   
        <p:dataTable id="${cc.attrs.id}" value="${cc.attrs.list}" var="object" summary="${cc.attrs.title}">     
            <f:facet name="header" rendered="#{not empty cc.attrs.title}">       
                <h:outputText value="${cc.attrs.title}" />             </f:facet>      
            <c:forEach items="#{cc.attrs.headers}" var="header" varStatus="loop">      
                <p:column headerText="${header}">               
                    <h:outputText value="${object[cc.attrs.props[loop.index]]}">
                    </h:outputText>     
                </p:column>  
            </c:forEach>    
            <composite:insertChildren />      
        </p:dataTable>     
    </composite:implementation> 
    
</html> 

dae_project_2017/dae_project_2017-war/web/resources/emcomp/entidate_edit.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" 
      xmlns:h="http://xmlns.jcp.org/jsf/html"  
      xmlns:composite="http://xmlns.jcp.org/jsf/composite"       
      xmlns:emcomp="http://xmlns.jcp.org/jsf/composite/emcomp">    

    <composite:interface>    
        <composite:attribute name="entidade" required="true"/> 
        <composite:attribute name="showPassword" type="boolean" default="false" required="false"/> 
    </composite:interface>    

    <composite:implementation>   

        <h:form>

            <emcomp:input_field
                id_tag="username"
                name_tag="Username: "
                value="${cc.attrs.entidade.username}" 
                is_disabled="true"/>

            <emcomp:input_pass
                id_tag="password"
                name_tag="Password: "
                rendered="#{cc.attrs.showPassword}"
                value="${cc.attrs.entidade.password}" />

            <emcomp:input_field
                id_tag="nome"
                name_tag="Nome: "
                value="${cc.attrs.entidade.nome}" />

            <emcomp:input_field
                id_tag="email"
                name_tag="Email: "
                value="${cc.attrs.entidade.email}" />

            <composite:insertChildren />

        </h:form>

    </composite:implementation> 

</html> 

dae_project_2017/dae_project_2017-war/web/resources/emcomp/input_date.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" 
      xmlns:h="http://xmlns.jcp.org/jsf/html" 
      xmlns:p="http://primefaces.org/ui" 
      xmlns:composite="http://xmlns.jcp.org/jsf/composite"       
          
      xmlns:f="http://xmlns.jcp.org/jsf/core">    

    <composite:interface>    
        <composite:attribute name="id_tag" required="true"/>
        <composite:attribute name="name_tag" required="true"/> 
        <composite:attribute name="value" required="false"/>
        <composite:attribute name="is_required" required="false" default="true"/> 
        <composite:attribute name="is_disabled" required="false" default="false"/> 
    </composite:interface>

    <composite:implementation>   

        <div class="form-group">
            <p:outputLabel 
                for="${cc.attrs.id_tag}"
                value="${cc.attrs.name_tag}" />
            
            <h:inputText 
                id="${cc.attrs.id_tag}"
                value="${cc.attrs.value}"
                class="form-control"
                required="${cc.attrs.is_required}"
                disabled="${cc.attrs.is_disabled}"
                >
                <f:convertDateTime pattern="yyyy-MM-dd"/>  
            </h:inputText>

            <h:message for="${cc.attrs.id_tag}" class="help-block" errorStyle="color: red" />
        </div>

    </composite:implementation> 

</html> 

dae_project_2017/dae_project_2017-war/web/resources/emcomp/input_field.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" 
      xmlns:h="http://xmlns.jcp.org/jsf/html" 
      xmlns:p="http://primefaces.org/ui" 
      xmlns:composite="http://xmlns.jcp.org/jsf/composite"       
      >    

    <composite:interface>    
        <composite:attribute name="id_tag" required="true"/>
        <composite:attribute name="name_tag" required="true"/> 
        <composite:attribute name="value" required="false"/>
        <composite:attribute name="is_required" required="false" default="true"/> 
        <composite:attribute name="is_disabled" required="false" default="false"/> 
    </composite:interface>

    <composite:implementation>   

        <div class="form-group">
            <p:outputLabel 
                for="${cc.attrs.id_tag}"
                value="${cc.attrs.name_tag}" />

            <h:inputText 
                id="${cc.attrs.id_tag}"
                value="${cc.attrs.value}"
                class="form-control"
                required="${cc.attrs.is_required}"
                disabled="${cc.attrs.is_disabled}"
                />

            <h:message for="${cc.attrs.id_tag}" class="help-block" errorStyle="color: red" />
        </div>

    </composite:implementation> 

</html> 

dae_project_2017/dae_project_2017-war/web/resources/emcomp/input_pass.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" 
      xmlns:h="http://xmlns.jcp.org/jsf/html" 
      xmlns:p="http://primefaces.org/ui" 
      xmlns:composite="http://xmlns.jcp.org/jsf/composite"       
      >    

    <composite:interface>    
        <composite:attribute name="id_tag" required="true"/>
        <composite:attribute name="name_tag" required="true"/> 
        <composite:attribute name="value" required="false"/> 
        <composite:attribute name="is_required" required="false" default="true"/> 
        <composite:attribute name="is_disabled" required="false" default="false"/> 
    </composite:interface>

    <composite:implementation>   

        <div class="form-group">
        <p:outputLabel 
            for="${cc.attrs.id_tag}"
            value="${cc.attrs.name_tag}" />

        <h:inputSecret
            id="${cc.attrs.id_tag}"
            value="${cc.attrs.value}"
            class="form-control"
            required="${cc.attrs.is_required}"
            disabled="${cc.attrs.is_disabled}"
            />

        <h:message for="${cc.attrs.id_tag}" class="help-block" errorStyle="color: red" />
</div>
    </composite:implementation> 

</html> 

dae_project_2017/dae_project_2017-war/web/resources/emcomp/input_tarea.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" 
      xmlns:h="http://xmlns.jcp.org/jsf/html" 
      xmlns:p="http://primefaces.org/ui" 
      xmlns:composite="http://xmlns.jcp.org/jsf/composite"       
      >    

    <composite:interface>    
        <composite:attribute name="id_tag" required="true"/>
        <composite:attribute name="name_tag" required="true"/> 
        <composite:attribute name="value" required="false"/> 
    </composite:interface>

    <composite:implementation>   

        <div class="form-group">
            
            <p:outputLabel 
                for="${cc.attrs.id_tag}"
                value="${cc.attrs.name_tag}" />
            
            <h:inputTextarea
                id="${cc.attrs.id_tag}"
                value="${cc.attrs.value}"
                class="form-control col-4"
                rows='3'
                />

            <h:message for="${cc.attrs.id_tag}" class="help-block" errorStyle="color: red" />

        </div>
        
    </composite:implementation> 

</html> 

dae_project_2017/dae_project_2017-war/web/resources/emcomp/proposta_update.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" 
      xmlns:h="http://xmlns.jcp.org/jsf/html" 
      xmlns:p="http://primefaces.org/ui" 
      xmlns:composite="http://xmlns.jcp.org/jsf/composite"     
      xmlns:em="http://xmlns.jcp.org/jsf/composite/emcomp"

      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:f="http://xmlns.jcp.org/jsf/core">    

    <composite:interface>
        <composite:attribute name="proposta" required="true"/> 
    </composite:interface>

    <composite:implementation>   

        <h:form>

            <em:input_field id_tag="titulo" name_tag="Titulo:" 
                            value="#{cc.attrs.proposta.titulo}"/>

            <br/>

            <em:input_field id_tag="resumo" name_tag="Resumo:" 
                            value="#{cc.attrs.proposta.resumo}"/>

            <br/>

            <em:view_field id_tag="tipo_trabalho" name_tag="Tipo de Trabalho:"
                           value="#{cc.attrs.proposta.tipoTrabalho.nomeTipo}"/>

            <br/>
            
            <p:outputLabel for="tipo_trabalho" value="Tipo de Trabalho" />
            <h:selectOneMenu id="tipo_trabalho" value="#{cc.attrs.proposta.tipoTrabalho}">
                <f:selectItems
                    value="#{proponenteManagedBean.allTiposDeTrabalho}"
                    var="tipoTrabalho"
                    itemValue="#{tipoTrabalho}"
                    itemLabel="#{tipoTrabalho}" />
            </h:selectOneMenu>
            
            <br/>

            <em:view_field id_tag="concurso_id" name_tag="Concurso Id: "
                           value="#{cc.attrs.proposta.concursoId}"/>

            <br/>

            <p:outputLabel value="Professores Proponentes" for="professores_proponentes"/>
            <h:selectManyCheckbox id="professores_proponentes" value="#{cc.attrs.proposta.proponenteUsernames}">
                <c:forEach items="#{proponenteManagedBean.allProfessores}" var="professor" >      
                    <f:selectItem itemValue="#{professor.username}" itemLabel="#{professor.nome}" />
                </c:forEach>   
            </h:selectManyCheckbox>
            <h:message for="professores_proponentes" errorStyle="color: red" />

            <br/>

            <em:view_string_list name_tag="Areas Cientificas:"
                                 list="#{cc.attrs.proposta.areasCientificas}"/>         

            <em:add_string_list list="#{cc.attrs.proposta.areasCientificas}" actionAdd=""
            <em:view_string_list name_tag="Objetivos:"
                                 list="#{cc.attrs.proposta.objectivos}"/>


            <c:if test="#{cc.attrs.proposta.tipoTrabalho.nomeTipo == 'Estágio'}">
                <em:input_field 
                    id_tag="local_realizacao"  
                    name_tag="Local Realizacao:"
                    value="#{cc.attrs.proposta.localRealizacao}"/>

                <br/>
            </c:if>


            <em:view_string_list name_tag="Requisitos:"
                                 list="#{cc.attrs.proposta.requisitosTrabalho}"/>


            <em:view_string_list name_tag="Apoios:"
                                 list="#{cc.attrs.proposta.apoios}"/>


            <p:outputLabel value="Orçamento"/>

            <br/>

            &nbsp;&nbsp;&nbsp;                
            <em:input_field
                id_tag="orcamento_bibliografia"
                name_tag="-Bibliografia:"
                value="#{cc.attrs.proposta.orcamentoBibliografia}"
                />&euro;

            <br/>

            &nbsp;&nbsp;&nbsp;               
            <em:input_field
                id_tag="orcamento_material"
                name_tag="-Material:"
                value="#{cc.attrs.proposta.orcamentoMaterial}"
                />&euro;

            <br/>

            &nbsp;&nbsp;&nbsp;
            <em:input_field
                id_tag="orcamento_equipamento"
                name_tag="-Equipamento:"
                value="#{cc.attrs.proposta.orcamentoEquipamento}"
                />&euro;

            <br/>

            &nbsp;&nbsp;&nbsp;
            <em:input_field
                id_tag="orcamento_outros"
                name_tag="-Outros:"
                value="#{cc.attrs.proposta.orcamentoOutros}"
                />&euro;

            <br/>

            <composite:insertChildren />    

        </h:form>

        <br/>

        <h:messages errorStyle="color: red" />    
    </composite:implementation> 

</html> 

dae_project_2017/dae_project_2017-war/web/resources/emcomp/view_field.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" 
      xmlns:h="http://xmlns.jcp.org/jsf/html" 
      xmlns:p="http://primefaces.org/ui" 
      xmlns:composite="http://xmlns.jcp.org/jsf/composite"       
      >    

    <composite:interface>    
        <composite:attribute name="id_tag" required="true"/>
        <composite:attribute name="name_tag" required="true"/> 
        <composite:attribute name="value" required="false"/> 
    </composite:interface>

    <composite:implementation>   

        <div class="form-group">
            <p:outputLabel 
                for="${cc.attrs.id_tag}"
                value="${cc.attrs.name_tag}" />
            
            <h:outputText 
                id="${cc.attrs.id_tag}"
                value="${cc.attrs.value}"/>
        </div>
    </composite:implementation> 

</html> 

dae_project_2017/dae_project_2017-war/web/resources/emcomp/view_string_list.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"  
      xmlns:p="http://primefaces.org/ui" 
      xmlns:composite="http://xmlns.jcp.org/jsf/composite"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">    

    <composite:interface> 
        <composite:attribute name="name_tag" required="true"/>
        <composite:attribute name="list" required="true"/> 
        <composite:attribute name="empty_value_override" required="false" default="Campo vazio!"/> 
    </composite:interface>

    <composite:implementation>   

        <div class="form-group">

            <p:outputLabel value="${cc.attrs.name_tag}"/>

            <ul>
                <c:forEach items="${cc.attrs.list}" var="area">
                    <li>${area}</li>
                </c:forEach>

                <c:if test="#{cc.attrs.list.size() == 0}">  
                    <li>${cc.attrs.empty_value_override}</li>
                </c:if>  
            </ul>

        </div>

    </composite:implementation> 

</html> 