dae_project_2017/dae_project_2017-war/src/java/web/ManageBeans/EstudanteManagedBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package web.ManageBeans;

import dtos.CandidaturaDTO;
import dtos.DocumentoDTO;
import dtos.EstudanteDTO;
import dtos.TrabalhoDTO;
import ejbs.CandidaturaBean;
import ejbs.EstudanteBean;
import ejbs.TrabalhoBean;
import javax.faces.component.UIComponent;
import javax.faces.component.UIParameter;
import javax.faces.event.ActionEvent;
import web.FacesExceptionHandler;
import java.io.Serializable;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.ws.rs.client.Entity;
import javax.ws.rs.core.GenericType;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import util.URILookup;
import utils.embeddable.Documento;

@ManagedBean
@SessionScoped
public class EstudanteManagedBean extends UserManagedBean<EstudanteDTO> implements Serializable {

    @ManagedProperty(value = "#{uploadManager}")
    private UploadManager uploadManager;
    
    private Response response;
    private UIComponent component;

    private TrabalhoDTO currentTrabalho;
    private CandidaturaDTO currentCandidatura;
    private CandidaturaDTO newCandidatura;

    // #######################################################################
    public EstudanteManagedBean() {
        super(EstudanteDTO.class);
        currentTrabalho = new TrabalhoDTO();
        currentCandidatura = new CandidaturaDTO();
        newCandidatura = new CandidaturaDTO();
    }

    // #######################################################################
    @Override
    protected String getRestPathToFindUser(String username) {
        return EstudanteBean.REST_PATH_GET_FIND(username);
    }

    // ####################################################
    //                                      CANDIDATURAS
    // ####################################################
    public void adicionarDocumentoNovaCandidatura(){
        if(uploadManager.getFile().getSize() == 0){
            FacesExceptionHandler.handleException(
                "Nenhum documento especificado",
                component, logger);
            return;
         }
            
        DocumentoDTO documentoDTO
                = new DocumentoDTO(
                        uploadManager.getFilename(),
                        new Date(), 
                        uploadManager.getCompletePathFile(),
                        uploadManager.getFile().getContentType()
                );
        newCandidatura.addDocumento(documentoDTO);

        uploadManager.setFile(null);
    }
    
    public void adicionarDocumentoCurrentCandidatura(){
        if(uploadManager.getFile().getSize() == 0){
            FacesExceptionHandler.handleException(
                "Nenhum documento especificado",
                component, logger);
            return;
         }            

        DocumentoDTO documentoDTO
                = new DocumentoDTO(
                        uploadManager.getFilename(),
                        new Date(), 
                        uploadManager.getCompletePathFile(),
                        uploadManager.getFile().getContentType()
                );
        currentCandidatura.addDocumento(documentoDTO);
        uploadManager.setFile(null);
    }

    public String createCandidatura() {
        newCandidatura.setEstudanteUsername(loginManagedBean.getUsername());
        newCandidatura.setTrabalhoId(currentTrabalho.getId());
        newCandidatura.setTrabalhoTitulo(currentTrabalho.getTitulo());

        if(newCandidatura.getDocumentos().isEmpty()){
            FacesExceptionHandler.handleException(
                "Nenhum documento especificado",
                component, logger);
            return null;
        }

        response = client.target(URILookup.getBaseAPI())
                .path(CandidaturaBean.REST_PATH_CREATE)
                .request(MediaType.APPLICATION_XML)
                .post(Entity.xml(newCandidatura));

        if (response.getStatusInfo().getFamily() != Response.Status.Family.SUCCESSFUL) {
            FacesExceptionHandler.handleException(
                    response, "Erro ao tentar criar a candidatura",
                    component, logger);
            return null;
        }

        newCandidatura.reset();
        uploadManager.setFile(null);
        return "estudante_index?faces-redirect=true";
    }

    public String updateCandidatura() {
        if(currentCandidatura.getDocumentos().isEmpty()){
            FacesExceptionHandler.handleException(
                "Nenhum documento especificado",
                component, logger);
            return null;
        }

        response = client.target(URILookup.getBaseAPI())
                .path(CandidaturaBean.REST_PATH_UPDATE)
                .request(MediaType.APPLICATION_XML)
                .put(Entity.xml(currentCandidatura));

        if (response.getStatusInfo().getFamily() != Response.Status.Family.SUCCESSFUL) {
            FacesExceptionHandler.handleException(
                    response, "Erro ao tentar atualizar a candidatura",
                    component, logger);
            return null;
        }
        
        currentCandidatura.reset();
        uploadManager.setFile(null);
        return "estudante_index?faces-redirect=true";
    }

    public Collection<CandidaturaDTO> getAllCandidaturasDoEstudante() {

        response = client.target(URILookup.getBaseAPI())
                .path(CandidaturaBean.REST_PATH_GET_ALL(loginManagedBean.getUsername()))
                .request(MediaType.APPLICATION_XML)
                .get();
        if (response.getStatusInfo().getFamily() != Response.Status.Family.SUCCESSFUL) {
            FacesExceptionHandler.handleException(
                    response,
                    "Erro ao carregar as candidaturas",
                    component, logger
            );
        }
        return response.readEntity(new GenericType<List<CandidaturaDTO>>() {});
    }

    public void removerCandidatura(ActionEvent event) {
        UIParameter param
                = (UIParameter) event.getComponent().findComponent("candidaturaID");
        String id = param.getValue().toString();

        response = client.target(URILookup.getBaseAPI())
                .path(CandidaturaBean.REST_PATH_DELETE(id))
                .request(MediaType.APPLICATION_XML)
                .delete();

        if (response.getStatusInfo().getFamily() != Response.Status.Family.SUCCESSFUL) {
            FacesExceptionHandler.handleException(
                    response,
                    "Erro ao remover a candidatura",
                    component, logger);
        }
    }
    // #######################################################################
    // TRABALHOS
    // #######################################################################

    public Collection<TrabalhoDTO> getAllTrabalhosEmPeriodoCandidatura() {
        response = client.target(URILookup.getBaseAPI())
                .path(TrabalhoBean.REST_PATH_GET_ALL_FASE_CANDIDATURA)
                .request(MediaType.APPLICATION_XML)
                .get();
        if (response.getStatusInfo().getFamily() != Response.Status.Family.SUCCESSFUL) {
            FacesExceptionHandler.handleException(
                    response,
                    "Erro ao carregar os trabalhos",
                    component, logger
            );
        }
        return response.readEntity(new GenericType<List<TrabalhoDTO>>() {});
    }
    
    public TrabalhoDTO getTrabalho(){
        response = client.target(URILookup.getBaseAPI())
                .path(EstudanteBean.REST_PATH_GET_TRABALHO(loginManagedBean.getUsername()))
                .request(MediaType.APPLICATION_XML)
                .get();
        if (response.getStatusInfo().getFamily() != Response.Status.Family.SUCCESSFUL) {
            FacesExceptionHandler.handleException(
                    response,
                    "Erro ao carregar o trabalho",
                    component, logger
            );
        }
        return response.readEntity(TrabalhoDTO.class);
    }
    
    public void adicionarArtefactoCurrentTrabalho(int tipoDeDocumento){
        if(uploadManager.getFile().getSize() == 0){
               FacesExceptionHandler.handleException(
                    "Nenhum documento especificado",
                    component, logger);
            return;
        }
            
        DocumentoDTO documentoDTO
                = new DocumentoDTO(
                        uploadManager.getFilename(),
                        new Date(), 
                        uploadManager.getCompletePathFile(),
                        uploadManager.getFile().getContentType()
                );
        System.err.println(tipoDeDocumento);
        if(tipoDeDocumento == 0){
            documentoDTO.setTipoDeDocumento(Documento.TipoDeDocumento.RELATORIO);
        } else {
            documentoDTO.setTipoDeDocumento(Documento.TipoDeDocumento.ARTEFACTO);
        }
        currentTrabalho.addArtefacto(documentoDTO);        
        uploadManager.setFile(null);
    }
    
    public String updateArtefactosTrabalho(){
        response = client.target(URILookup.getBaseAPI())
                .path(TrabalhoBean.REST_PATH_UPDATE_ARTEFACTOS)
                .request(MediaType.APPLICATION_XML)
                .put(Entity.xml(currentTrabalho));

        if (response.getStatusInfo().getFamily() != Response.Status.Family.SUCCESSFUL) {
            FacesExceptionHandler.handleException(
                    response, "Erro ao tentar atualizar os artefactos de trabalho",
                    component, logger);
            return null;
        }
        
        currentTrabalho.reset();
        uploadManager.setFile(null);

dae_project_2017/dae_project_2017-war/web/roles/estudante/estudante_candidatura_details.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"           
      xmlns:em="http://xmlns.jcp.org/jsf/composite/emcomp"            
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"       >      

    <ui:composition template="../../templates/skeleton.xhtml">

        <ui:define name="title">
            Detalhes de Candidatura
        </ui:define>

        <ui:define name="main">
            <h:form>
                <em:input_field
                    id_tag="trabalho" 
                    value="#{estudanteManagedBean.currentCandidatura.trabalhoTitulo}" 
                    name_tag="Trabalho:"
                    is_disabled="true"
                    is_required="false"/>

                <em:input_field
                    id_tag="media"
                    name_tag="Media:"
                    value="#{estudanteManagedBean.currentCandidatura.media}"
                    is_disabled="true"
                    is_required="false"/>

                <div class="form-group">
                    <em:dt 
                        title="Documentos da Candidatura"
                        id="documentos"
                        headers="#{['Nome', 'Tipo', 'Data']}" 
                        props="#{['nome','mimeType','uploadedAt']}" 
                        list="#{estudanteManagedBean.currentCandidatura.documentos}">

                        <p:column headerText="Acções">     
                            <h:form>
                                <p:commandButton value="Download" ajax="false">
                                    <p:fileDownload value="#{downloadManager.getFile(object)}" />
                                </p:commandButton>
                            </h:form>
                        </p:column> 

                    </em:dt>
                </div>
                
                <div class="form-group">
                    <h:link
              
                        value="Voltar" 
                        outcome="estudante_index?faces-redirect=true"
                        class="btn btn-primary"/>

                    <h:message for="submit" class="help-block" style="color: red"/>
                </div>

            </h:form>
        </ui:define>
    </ui:composition>

</html> 

dae_project_2017/dae_project_2017-war/web/roles/estudante/estudante_candidatura_trabalho_create.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"                       
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:em="http://xmlns.jcp.org/jsf/composite/emcomp"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">      

    <ui:composition template="../../templates/skeleton.xhtml">

        <ui:define name="title">
            Criar Candidatura
        </ui:define>

        <ui:define name="main">

            <h:form enctype="multipart/form-data">

                <em:input_field
                    id_tag="trabalho" 
                    name_tag="Trabalho:"
                    value="#{estudanteManagedBean.currentTrabalho.titulo}" 
                    is_disabled="true"
                    is_required="false"/>

                <div class="form-group">
                    <em:dt 
                        title="Documentos de candidatura"
                        id="documents"
                        headers="#{['Nome', 'Tipo', 'Data']}" 
                        props="#{['nome','mimeType','uploadedAt']}" 
                        list="#{estudanteManagedBean.newCandidatura.documentos}">

                        <p:column headerText="Acções">
                            <p:commandButton value="Download" ajax="false">
                                <p:fileDownload value="#{downloadManager.getFile(object)}" />
                            </p:commandButton>
                            &nbsp;
                            <p:commandButton
                                value="Remover"
                                update="documents"
                                action="${estudanteManagedBean.newCandidatura.removeDocumento(object)}" />
                        </p:column> 
                    </em:dt>
                </div>

                <div class="form-group">
                    <p:growl id="growlcv" showDetail="true" />
                    <p:fileUpload
                        value="#{uploadManager.file}" 
                        mode="simple" 
                        skinSimple="true"/>
                </div>

                <div class="form-group">
                    <p:commandButton value="Carregar" 
                                     ajax="false" 
                                     actionListener="#{uploadManager.upload('candidaturas/')}"
                                     action="#{estudanteManagedBean.adicionarDocumentoNovaCandidatura()}"/>
                </div>
            </h:form>
            <h:form>


                <em:input_field id_tag="media" name_tag="Média:" 
                                value="#{estudanteManagedBean.newCandidatura.media}"/>

                <div class="form-group">
                    <h:link 
                        value="Cancelar"
                        outcome="estudante_index?faces-redirect=true"
                        class="btn btn-danger"/>
                    
                    &nbsp;
                    
                    <h:commandButton
                        id="submit"
                        value="Criar Candidatura"
                        class="btn btn-primary"
                        binding="#{estudanteManagedBean.component}"
                        action="#{estudanteManagedBean.createCandidatura()}" />
                    <p:message for="submit" style="color: red"/>
                </div>
            </h:form>

        </ui:define>
    </ui:composition>

</html> 

dae_project_2017/dae_project_2017-war/web/roles/estudante/estudante_candidatura_update.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"           
      xmlns:em="http://xmlns.jcp.org/jsf/composite/emcomp"            
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html">      

    <ui:composition template="../../templates/skeleton.xhtml">

        <ui:define name="title">
            Atualizar Candidatura
        </ui:define>

        <ui:define name="main">

            <h:form enctype="multipart/form-data">
                <em:input_field
                    id_tag="trabalho" 
                    value="#{estudanteManagedBean.currentCandidatura.trabalhoTitulo}" 
                    name_tag="Título do Trabalho"
                    is_disabled="true"
                    is_required="false"/>

                <div class="form-group">
                    <em:dt 
                        title="Documentos de candidatura"
                        id="documents"
                        headers="#{['Nome', 'Tipo', 'Data']}" 
                        props="#{['nome','mimeType','uploadedAt']}" 
                        list="#{estudanteManagedBean.currentCandidatura.documentos}">

                        <p:column headerText="Acções">
                            <p:commandButton value="Download" ajax="false">
                                <p:fileDownload value="#{downloadManager.getFile(object)}" />
                            </p:commandButton>
                            &nbsp;
                            <p:commandButton
                                value="Remover"
                                update="documents"
                                action="${estudanteManagedBean.currentCandidatura.removeDocumento(object)}" />
                        </p:column> 
                    </em:dt>
                </div>

                <div class="form-group">
                    <p:growl id="growlcv" showDetail="true" />
                    <p:fileUpload
                        value="#{uploadManager.file}" 
                        mode="simple" 
                        skinSimple="true"/>
                </div>

                <div class="form-group">
                    <p:commandButton value="Carregar" 
                                     ajax="false" 
                                     actionListener="#{uploadManager.upload('candidaturas/')}"
                                     action="#{estudanteManagedBean.adicionarDocumentoCurrentCandidatura()}"/>
                </div>
                <br/>
            </h:form>
            <h:form>

                <div class="form-group">
                    <em:input_field id_tag="media" name_tag="Media:" 
                                    value="#{estudanteManagedBean.currentCandidatura.media}"/>
                </div>

                <br/>

                <div class="form-group">
                    <h:commandLink 
                        value="Cancelar" 
                        actionListener="#{estudanteManagedBean.currentCandidatura.reset()}"
                        action="estudante_index?faces-redirect=true"
                        class="btn btn-danger" />
                    &nbsp;
                    <h:commandButton
                        id="submit"
                        value="Atualizar Candidatura"
                        class="btn btn-primary"
                        binding="#{estudanteManagedBean.component}"
                        action="#{estudanteManagedBean.updateCandidatura()}" />
                    <p:message for="submit" style="color: red"/>
                </div>
            </h:form>
        </ui:define>
    </ui:composition>

</html> 

dae_project_2017/dae_project_2017-war/web/roles/estudante/estudante_index.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"       
      xmlns:h="http://xmlns.jcp.org/jsf/html"       
      xmlns:f="http://java.sun.com/jsf/core"       
      xmlns:p="http://primefaces.org/ui"       
      xmlns:em="http://xmlns.jcp.org/jsf/composite/emcomp"            
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">      

    <ui:composition template="../../templates/skeleton.xhtml">

        <ui:define name="title">
            Index #{loginManagedBean.username}
        </ui:define>

        <ui:define name="main">
            
            <c:if test="#{loginManagedBean.latestConcurso.estadoConcurso.nomeTipo.equalsIgnoreCase(loginManagedBean.ESTADO_CONCURSO_PERIODO_MARCACAO_PROVA_PUBLICA)}">
                <em:dt 
                    title="Trabalho Entregue"
                    id="trabalhos_entregues"
                    headers="#{['Titulo Trabalho', 'Tipo de Trabalho', 'Resumo']}" 
                    props="#{['titulo','tipoTrabalho','resumo']}" 
                    list="#{estudanteManagedBean.trabalho}">

                    <p:column headerText="Acções">     
                        <h:form>
                            <h:commandLink value="Detalhes" action="estudante_trabalho_atribuido_details?faces-redirect=true" >
                                <f:setPropertyActionListener target="#{estudanteManagedBean.currentTrabalho}" value="#{object}"/>
                            </h:commandLink>
                        </h:form>
                    </p:column> 
                </em:dt>

                <br/>
                <br/>
            </c:if>

            <c:if test="#{loginManagedBean.latestConcurso.estadoConcurso.nomeTipo.equalsIgnoreCase(loginManagedBean.ESTADO_CONCURSO_PERIODO_ENTREGA_TRABALHOS)}">
                <em:dt 
                    title="Minha Proposta de Trabalho"
                    id="propostas"
                    headers="#{['Titulo Trabalho', 'Tipo de Trabalho', 'Resumo']}" 
                    props="#{['titulo','tipoTrabalho','resumo']}" 
                    list="#{estudanteManagedBean.trabalho}">

                    <p:column headerText="Acções">     
                        <h:form>
                            <h:commandLink value="Detalhes" action="estudante_trabalho_atribuido_details?faces-redirect=true" >
                                <f:setPropertyActionListener target="#{estudanteManagedBean.currentTrabalho}" value="#{object}"/>
                            </h:commandLink>
                        </h:form>
                    </p:column> 
                </em:dt>

                <br/>
                <br/>
            </c:if>

            <c:if test="#{not loginManagedBean.latestConcurso.estadoConcurso.nomeTipo.equalsIgnoreCase(loginManagedBean.ESTADO_CONCURSO_PERIODO_CANDIDATURAS)}">
                <em:dt
                    id="candidaturas"
                    title="Minhas candidaturas a trabalhos" 
                    headers="#{['Estudante', 'Titulo Trabalho', 'Média']}" 
                    props="#{['estudanteUsername','trabalhoTitulo', 'media']}" 
                    list="#{estudanteManagedBean.allCandidaturasDoEstudante}">

                    <p:column headerText="Acções">     
                        <h:form>
                            <h:commandLink value="Detalhes" action="estudante_candidatura_details?faces-redirect=true" >
                                <f:setPropertyActionListener target="#{estudanteManagedBean.currentCandidatura}" value="#{object}"/>
                            </h:commandLink>
                        </h:form>
                    </p:column> 
                </em:dt> 

                <br/>
                <br/>
            </c:if>

            <c:if test="#{loginManagedBean.latestConcurso.estadoConcurso.nomeTipo.equalsIgnoreCase(loginManagedBean.ESTADO_CONCURSO_PERIODO_CANDIDATURAS)}">
                <em:dt 
                    id="minhas_candidaturas"
                    title="Minhas candidaturas a trabalhos" 
                    headers="#{['Estudante', 'Titulo Trabalho', 'Média']}" 
                    props="#{['estudanteUsername','trabalhoTitulo', 'media']}" 
                    list="#{estudanteManagedBean.allCandidaturasDoEstudante}">

                    <p:column headerText="Acções">     
                        <h:form>
                            <h:commandLink value="Detalhes" action="estudante_candidatura_details?faces-redirect=true" >
                                <f:setPropertyActionListener target="#{estudanteManagedBean.currentCandidatura}" value="#{object}"/>
                            </h:commandLink>
                            &nbsp;
                            <h:commandLink value="Atualizar" action="estudante_candidatura_update?faces-redirect=true" >
                                <f:setPropertyActionListener target="#{estudanteManagedBean.currentCandidatura}" value="#{object}"/>
                            </h:commandLink>
                            &nbsp;
                            <h:commandLink value="Remover" actionListener="#{estudanteManagedBean.removerCandidatura}">
                                <f:param name="candidaturaID" id="candidaturaID" value="#{object.id}" />
                            </h:commandLink>

                        </h:form>
                    </p:column> 
                </em:dt> 

                <br/>
                <br/>

                <em:dt 
                    id="trabalhos_disponiveis"
                    title="Trabalhos disponiveis" 
                    headers="#{['Titulo Trabalho', 'Tipo de Trabalho', 'Resumo']}" 
                    props="#{['titulo','tipoTrabalho','resumo']}" 
                    list="#{estudanteManagedBean.allTrabalhosEmPeriodoCandidatura}">  

                    <p:column headerText="Acções">     
                        <h:form>
                            <h:commandLink value="Candidatar" rendered="#{not estudanteManagedBean.temCandidaturaATrabalho(object.id)}" action="estudante_candidatura_trabalho_create?faces-redirect=true" >
                                <f:setPropertyActionListener target="#{estudanteManagedBean.currentTrabalho}" value="#{object}"/>
                            </h:commandLink>
                            &nbsp;
                            <h:commandLink value="Detalhes" action="estudante_trabalho_candidataveil_details?faces-redirect=true" >
                                <f:setPropertyActionListener target="#{estudanteManagedBean.currentTrabalho}" value="#{object}"/>
                            </h:commandLink>
                        </h:form>
                    </p:column> 
                </em:dt> 

                <br/>
                <br/>
            </c:if>

        </ui:define>
    </ui:composition>

</html> 

dae_project_2017/dae_project_2017-war/web/roles/estudante/estudante_trabalho_candidataveil_details.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"       
      xmlns:h="http://xmlns.jcp.org/jsf/html"                     
      xmlns:em="http://xmlns.jcp.org/jsf/composite/emcomp"            
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:p="http://primefaces.org/ui">      

    <ui:composition template="../../templates/skeleton.xhtml">

        <ui:define name="title">
            Detalhes do Trabalho
        </ui:define>

        <ui:define name="main">
            <h:form>
                <em:input_field
                    id_tag="titulo" 
                    name_tag="Titulo"
                    value="#{estudanteManagedBean.currentTrabalho.titulo}"
                    is_disabled="true"
                    is_required="false"/>

                <em:input_field
                    id_tag="tipo_trabalho" 
                    name_tag="Tipo de Trabalho"
                    value="#{estudanteManagedBean.currentTrabalho.tipoTrabalho.nomeTipo}"
                    is_disabled="true"
                    is_required="false"/>

                <c:if test="#{estudanteManagedBean.currentTrabalho.tipoTrabalho.nomeTipo == 'Estágio'}">
                    <em:input_field
                        id_tag="local_realizacao"  
                        name_tag="Local Realizacao"
                        value="#{estudanteManagedBean.currentTrabalho.proposta.localRealizacao != null ? 
                                 estudanteManagedBean.currentTrabalho.proposta.localRealizacao : 'Por definir'}"
                        is_disabled="true"
                        is_required="false"/>

                </c:if>

                <em:input_field
                    id_tag="resumo" 
                    name_tag="Resumo"
                    value="#{estudanteManagedBean.currentTrabalho.resumo}"
                    is_disabled="true"
                    is_required="false"/>
                
                <em:input_field
                    id_tag="plano_trabalho" 
                    name_tag="Plano de Trabalho"
                    value="#{estudanteManagedBean.currentTrabalho.proposta.planoTrabalho}"
                    is_disabled="true"
                    is_required="false"/>

                <em:view_string_list 
                    name_tag="Professores"
                    list="#{estudanteManagedBean.currentTrabalho.professorUsernames}"
                    empty_value_override="Ainda nao foram alocados professores para este trabalho"/>         

                <em:view_string_list 
                    name_tag="Areas Cientificas"
                    list="#{estudanteManagedBean.currentTrabalho.proposta.areasCientificas}"/>    


                <em:view_string_list 
                    name_tag="Objetivos"
                    list="#{estudanteManagedBean.currentTrabalho.proposta.objectivos}"/>


                <em:view_string_list 
                    name_tag="Requisitos"
                    list="#{estudanteManagedBean.currentTrabalho.proposta.requisitosTrabalho}"/>


                <em:view_string_list 
                    name_tag="Apoios"
                    list="#{estudanteManagedBean.currentTrabalho.proposta.apoios}"/>

                <div class="form-group">
                    <p:outputLabel value="Bibliografia"/>
                    <ul>
                        <c:forEach items="${estudanteManagedBean.currentTrabalho.proposta.bibliografia}" var="area">
                            <li>
                                <span>${area.titulo},&nbsp;${area.autor}</span>
                            </li>
                        </c:forEach>

                        <c:if test="#{estudanteManagedBean.currentTrabalho.proposta.bibliografia.size() == 0}">  
                            <li>"Campo vazio!"</li>
                        </c:if>  
                    </ul>
                </div>
                
                <h:link value="Voltar" 
                        outcome="estudante_index"
                        class="btn btn-primary" 
                        />

            </h:form>
        </ui:define>
    </ui:composition>

</html> 