dae_project_2017/dae_project_2017-war/src/java/web/ManageBeans/ProponenteManagedBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package web.ManageBeans;

import dtos.InstituicaoDTO;
import dtos.ProfessorDTO;
import dtos.ProponenteDTO;
import dtos.PropostaDTO;
import dtos.SupervisorDTO;
import ejbs.ConfigBean;
import ejbs.InstituicaoBean;
import ejbs.ProfessorBean;
import ejbs.ProponenteBean;
import ejbs.PropostaBean;
import ejbs.SupervisorBean;
import java.util.logging.Logger;
import web.FacesExceptionHandler;
import java.io.Serializable;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.component.UIParameter;
import javax.faces.event.ActionEvent;
import javax.ws.rs.client.Entity;
import javax.ws.rs.core.GenericType;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import util.URILookup;
import utils.TipoTrabalho;

/**
 *
 * @author vsc
 */
@ManagedBean
@SessionScoped
public class ProponenteManagedBean extends UserManagedBean<ProponenteDTO> implements Serializable {

    private UIComponent component;
    private Response response;
    private SupervisorDTO newSupervisor;
    private PropostaDTO currentProposta;
    private PropostaDTO newProposta;

    // #######################################################################
    public ProponenteManagedBean() {
        super(ProponenteDTO.class);
        this.logger = Logger.getLogger("web.ProponenteManagedBean");
        newSupervisor = new SupervisorDTO();
        currentProposta = new PropostaDTO();
        newProposta = new PropostaDTO();
    }
    
    // #######################################################################
    @Override
    protected String getRestPathToFindUser(String username) {
        return ProponenteBean.REST_PATH_GET_FIND(username);
    }

    // #######################################################################
    public Collection<PropostaDTO> getAllPropostasDoProponenteLoggado() {
        response = client.target(URILookup.getBaseAPI())
                    .path(ProponenteBean.REST_PATH_GET_PROPOSTAS(loginManagedBean.getUsername()))
                    .request(MediaType.APPLICATION_XML)
                    .get();
            
        if (response.getStatusInfo().getFamily() != Response.Status.Family.SUCCESSFUL) {
            FacesExceptionHandler.handleException(
                    response,
                    "Erro ao carregar as propostas do proponente loggado!",
                    component,
                    logger
            );

        }
        List<PropostaDTO> dtos = response.readEntity(new GenericType<List<PropostaDTO>>() {});
        return dtos;
    }
    
    public String createProposta() {
        newProposta.setMestrado(ConfigBean.MESTRADO);
        
        newProposta.removeProponenteUsername(loginManagedBean.getUsername());
        
        newProposta.addProponenteUsername(loginManagedBean.getUsername());
        newProposta.setConcursoId(loginManagedBean.getLatestConcurso().getId());
        
        
        response = client.target(URILookup.getBaseAPI())
                .path(PropostaBean.REST_PATH_CREATE)
                .request(MediaType.APPLICATION_XML)
                .post(Entity.xml(newProposta));

        if (response.getStatusInfo().getFamily() != Response.Status.Family.SUCCESSFUL) {
            FacesExceptionHandler.handleException(
                    response, "Erro ao tentar criar a proposta", 
                    component, logger);
            return null;
        }
        
        newProposta.reset();
        return "proponente_index?faces-redirect=true";
    }

    
    public String updateProposta() {
        currentProposta.setMestrado(ConfigBean.MESTRADO);
        
        currentProposta.removeProponenteUsername(loginManagedBean.getUsername());
        currentProposta.addProponenteUsername(loginManagedBean.getUsername());
        currentProposta.setConcursoId(loginManagedBean.getLatestConcurso().getId());
        
        response = client.target(URILookup.getBaseAPI())
                .path(PropostaBean.REST_PATH_UPDATE)
                .request(MediaType.APPLICATION_XML)
                .put(Entity.xml(currentProposta));

        if (response.getStatusInfo().getFamily() != Response.Status.Family.SUCCESSFUL) {
            FacesExceptionHandler.handleException(
                    response, 
                    "Erro ao tentar atualizar a proposta!", 
                    component, logger);
            return null;
        }
        currentProposta.reset();
        return "proponente_index?faces-redirect=true";
    }
    
    public void removeProposta(ActionEvent event) {
        UIParameter param 
                = (UIParameter) event.getComponent().findComponent("propostaId");
        //propostaBean.remove((Long) param.getValue());
        String id = param.getValue().toString();

        response = client.target(URILookup.getBaseAPI())
                .path(PropostaBean.REST_PATH_DELETE(id))
                .request(MediaType.APPLICATION_XML)
                .delete();

        if (response.getStatusInfo().getFamily() != Response.Status.Family.SUCCESSFUL) {
            FacesExceptionHandler.handleException(
                    response,
                    "Erro ao tentar remover a proposta",
                    component, logger);
        }
    }
    
    public List<TipoTrabalho> getAllTiposDeTrabalho() {
        try {
            return Arrays.asList(TipoTrabalho.values());
        } catch (Exception e) {
            FacesExceptionHandler.handleException(
                    e,
                    "Erro ao carregar os tipos de trabalho!",
                   component,  logger
            );
            return null;
        }
    }
    
    /*##################################################################
                                                            PROFESSORES
    #####################################################################*/
    
    public Collection<ProfessorDTO> getAllProfessores() {
        response = client.target(URILookup.getBaseAPI())
                .path(ProfessorBean.REST_PATH_GET_ALL)
                .request(MediaType.APPLICATION_XML)
                .get();

        if (response.getStatusInfo().getFamily() != Response.Status.Family.SUCCESSFUL) {
            FacesExceptionHandler.handleException(
                    response,
                    "Erro ao carregar todos os professores!",
                    component, logger
            );
        }
        return response.readEntity(new GenericType<List<ProfessorDTO>>() {});
    }
      /*##################################################################
                                                            SUPERVISORES
    #####################################################################*/
    public boolean isInstituicao(){
        try {
             InstituicaoDTO instDTO = client.target(URILookup.getBaseAPI())
                    .path(InstituicaoBean.REST_PATH_GET_FIND(loginManagedBean.getUsername()))
                    .request(MediaType.APPLICATION_XML)
                    .get(InstituicaoDTO.class);
             return instDTO != null;
        } catch (Exception e) {
            return false;
        }
    }
    
    public Collection<SupervisorDTO> getAllSupervisorsOfInstituicao(){
        response = client.target(URILookup.getBaseAPI())
                .path(SupervisorBean.REST_PATH_GET_ALL_DE_INSTITUICAO(loginManagedBean.getUsername()))
                .request(MediaType.APPLICATION_XML)
                .get();
        if (response.getStatusInfo().getFamily() != Response.Status.Family.SUCCESSFUL) {
            FacesExceptionHandler.handleException(
                    response,
                    "Erro ao carregar os supervisores da instituicao",
                    component, logger
            );
        }
        return response.readEntity(new GenericType<List<SupervisorDTO>>() {});
    } 
    
    public String createSupervisor() {
        newSupervisor.setInstituicaoUsername(loginManagedBean.getUsername());
        response = client.target(URILookup.getBaseAPI())
                .path(SupervisorBean.REST_PATH_PUT_CREATE)
                .request(MediaType.APPLICATION_XML)
                .put(Entity.xml(newSupervisor));

        if (response.getStatusInfo().getFamily() != Response.Status.Family.SUCCESSFUL) {
            FacesExceptionHandler.handleException(
                    response,
                    "Erro ao criar supervisor!",
                    component, logger
            );
            return null; // todo erros nao aparecem : e.g. username ja existe ou mail 
        }
        
        newSupervisor.reset();
        return "proponente_index?faces-redirect=true";
    }
    
    public UIComponent getComponent() {
        return component;
    }

    public void setComponent(UIComponent component) {
        this.component = component;
    }

    public PropostaDTO getCurrentProposta() {
        return currentProposta;
    }

    public void setCurrentProposta(PropostaDTO currentProposta) {
        this.currentProposta = currentProposta;
    }

    public PropostaDTO getNewProposta() {
        return newProposta;
    }

    public void setNewProposta(PropostaDTO newProposta) {
        this.newProposta = newProposta;
    }

    public SupervisorDTO getNewSupervisor() {
        return newSupervisor;
    }

    public void setNewSupervisor(SupervisorDTO newSupervisor) {
        this.newSupervisor = newSupervisor;
    }
    
    
}

dae_project_2017/dae_project_2017-war/web/roles/membro_ccp/membro_ccp_estudantes_create.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"       
      xmlns:h="http://xmlns.jcp.org/jsf/html"                       
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:emcomp="http://xmlns.jcp.org/jsf/composite/emcomp">     

    <ui:composition template="../../templates/skeleton.xhtml">

        <ui:define name="title"> 
            Criar Estudante
        </ui:define>

        <ui:define name="main"> 

            <h:form class="form-horozontal">                  

                <emcomp:input_field
                    id_tag="username"
                    name_tag="Username: "
                    value="#{membroComissaoCPManagedBean.newEstudante.username}" />

                <emcomp:input_field
                    id_tag="nome"
                    name_tag="Nome: "
                    value="#{membroComissaoCPManagedBean.newEstudante.nome}" />

                <emcomp:input_field
                    id_tag="email"
                    name_tag="Email: "
                    value="#{membroComissaoCPManagedBean.newEstudante.email}" />

                <div class="form-group">
                    
                    <h:link value="Cancelar" 
                            outcome="membro_ccp_index"
                            class="btn btn-danger" 
                            />

                    &nbsp;
                    
                    <h:commandButton
                        id="submit"
                        value="Criar"
                        class="btn btn-primary"
                        binding="#{membroComissaoCPManagedBean.component}"
                        action="#{membroComissaoCPManagedBean.createEstudante()}" />
                    <h:message for="submit" class="help-block" style="color: red"/>

                </div>
                
            </h:form>

            <h:messages errorStyle="color: red" />        

        </ui:define>
    </ui:composition>
</html>

dae_project_2017/dae_project_2017-war/web/roles/membro_ccp/membro_ccp_estudantes_update.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"       
      xmlns:h="http://xmlns.jcp.org/jsf/html"           
      xmlns:em="http://xmlns.jcp.org/jsf/composite/emcomp"            
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">     

    <ui:composition template="../../templates/skeleton.xhtml">

        <ui:define name="title"> 
            Atualizar Estudante
        </ui:define>
        
        <ui:define name="main"> 

            <em:entidate_edit entidade="${membroComissaoCPManagedBean.currentEstudante}">                  

                <h:link value="Cancelar" 
                    outcome="membro_ccp_index"
                    class="btn btn-danger" 
                    />
                
                &nbsp;
                
                <h:commandButton
                    id="submit"
                    value="Update"
                    class="btn btn-primary"
                    binding="#{membroComissaoCPManagedBean.component}"
                    action="#{membroComissaoCPManagedBean.updateEstudante}" />
                <h:message for="submit" class="help-block" style="color: red"/>
                
            </em:entidate_edit>

            <h:messages errorStyle="color: red" />        
        </ui:define>
    </ui:composition>
</html>

dae_project_2017/dae_project_2017-war/web/roles/membro_ccp/membro_ccp_instituicao_create.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"       
      xmlns:h="http://xmlns.jcp.org/jsf/html"                       
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:emcomp="http://xmlns.jcp.org/jsf/composite/emcomp">     

    <ui:composition template="../../templates/skeleton.xhtml">

        <ui:define name="title"> 
            Criar Instituição
        </ui:define>

        <ui:define name="main"> 

            <h:form>

                <emcomp:input_field
                    id_tag="username"
                    name_tag="Username: "
                    value="#{membroComissaoCPManagedBean.newInstituicao.username}" />

                <emcomp:input_field
                    id_tag="nome"
                    name_tag="Nome: "
                    value="#{membroComissaoCPManagedBean.newInstituicao.nome}" />

                <emcomp:input_field
                    id_tag="email"
                    name_tag="Email: "
                    value="#{membroComissaoCPManagedBean.newInstituicao.email}" />

                <emcomp:input_field
                    id_tag="tipoInstituicao"
                    name_tag="tipoInstituicao"
                    value="#{membroComissaoCPManagedBean.newInstituicao.tipoInstituicao}" />

                <div class="form-group">
                    <h:link value="Cancelar" 
                            outcome="membro_ccp_index"
                            class="btn btn-danger" 
                            />
                    &nbsp;   
                    <h:commandButton
                        id="submit"
                        value="Criar"
                        class="btn btn-primary"
                        binding="#{membroComissaoCPManagedBean.component}"
                        action="#{membroComissaoCPManagedBean.createInstituicao()}" />
                    <h:message for="submit" class="help-block" style="color: red"/>
                </div>
                
            </h:form>

            <h:messages errorStyle="color: red" />        

        </ui:define>
    </ui:composition>
</html>

dae_project_2017/dae_project_2017-war/web/roles/membro_ccp/membro_ccp_instituicoes_update.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"       
      xmlns:h="http://xmlns.jcp.org/jsf/html"       
      xmlns:f="http://java.sun.com/jsf/core"              
      xmlns:em="http://xmlns.jcp.org/jsf/composite/emcomp"            
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">     

    <ui:composition template="../../templates/skeleton.xhtml">

        <ui:define name="title"> 
            Atualizar Instituição
        </ui:define>

        <ui:define name="main"> 

            <em:entidate_edit entidade="${membroComissaoCPManagedBean.currentInstituicao}">                  

                <div class="form-group">

                    <h:link 
                        value="Cancelar" 
                        outcome="membro_ccp_index"
                        class="btn btn-danger" 
                        />
                    
                    &nbsp;
                    
                    <h:commandButton
                        id="submit"
                        value="Update"
                        class="btn btn-primary"
                        binding="#{membroComissaoCPManagedBean.component}"
                        action="#{membroComissaoCPManagedBean.updateInstituicao}" />
                    <h:message for="submit" style="color: red"/>

                </div>

            </em:entidate_edit>

            <h:messages errorStyle="color: red" />
            
        </ui:define>
    </ui:composition>
</html>


dae_project_2017/dae_project_2017-war/web/roles/membro_ccp/membro_ccp_professor_create.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"       
      xmlns:h="http://xmlns.jcp.org/jsf/html"                       
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:emcomp="http://xmlns.jcp.org/jsf/composite/emcomp">     

    <ui:composition template="../../templates/skeleton.xhtml">

        <ui:define name="title"> 
            Criar Professor
        </ui:define>

        <ui:define name="main"> 

            <h:form>                  

                <emcomp:input_field
                    id_tag="username"
                    name_tag="Username: "
                    value="#{membroComissaoCPManagedBean.newProfessor.username}" 
                    is_required="true"/>

                <emcomp:input_field
                    id_tag="nome"
                    name_tag="Nome: "
                    value="#{membroComissaoCPManagedBean.newProfessor.nome}"
                    is_required="true"/>

                <emcomp:input_field
                    id_tag="email"
                    name_tag="Email: "
                    value="#{membroComissaoCPManagedBean.newProfessor.email}"
                    is_required="true"/>

                <div class="form-group">
                    <h:link 
                        value="Cancelar" 
                        outcome="membro_ccp_index"
                        class="btn btn-danger" 
                        />

                    &nbsp;   

                    <h:commandButton
                        id="submit"
                        value="Criar"
                        class="btn btn-primary"
                        binding="#{membroComissaoCPManagedBean.component}"
                        action="#{membroComissaoCPManagedBean.createProfessor()}" />
                    <h:message for="submit" class="help-block" style="color: red"/>
                </div>
                
            </h:form>

            <h:messages errorStyle="color: red" />        

        </ui:define>
    </ui:composition>
</html>


dae_project_2017/dae_project_2017-war/web/roles/membro_ccp/membro_ccp_professores_update.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"       
      xmlns:h="http://xmlns.jcp.org/jsf/html"             
      xmlns:em="http://xmlns.jcp.org/jsf/composite/emcomp"            
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">     

    <ui:composition template="../../templates/skeleton.xhtml">

        <ui:define name="title"> 
            Atualizar Professor
        </ui:define>

        <ui:define name="main"> 

            <em:entidate_edit entidade="${membroComissaoCPManagedBean.currentProfessor}">                  

                <div class="form-group">
                    
                    <h:link value="Cancelar" 
                            outcome="membro_ccp_index"
                            class="btn btn-danger" 
                            />
                    
                    &nbsp;              
                    
                    <h:commandButton
                        id="submit"
                        value="Update"
                        class="btn btn-primary" 
                        binding="#{membroComissaoCPManagedBean.component}"
                        action="#{membroComissaoCPManagedBean.updateProfessor}" />
                    <h:message for="submit" class="help-block" style="color: red"/>
                
                </div>
                
            </em:entidate_edit>

            <h:messages errorStyle="color: red" />        
        </ui:define>
    </ui:composition>
</html>



dae_project_2017/dae_project_2017-war/web/roles/membro_ccp/membro_ccp_proposta_details.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"       
      xmlns:h="http://xmlns.jcp.org/jsf/html"             
      xmlns:em="http://xmlns.jcp.org/jsf/composite/emcomp"            
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">     

    <ui:composition template="../../templates/skeleton.xhtml">

        <ui:define name="title"> 
            Detalhes Proposta
        </ui:define>

        <ui:define name="main"> 

            <em:proposta_details proposta="#{membroComissaoCPManagedBean.currentProposta}">


                <c:if test="#{membroComissaoCPManagedBean.currentProposta.estado.nomeTipo == 'Análise'
                              and loginManagedBean.latestConcurso.estadoConcurso.nomeTipo.equalsIgnoreCase(loginManagedBean.ESTADO_CONCURSO_PERIODO_VALIDACAO)}">               
                    <em:input_tarea
                        id_tag="observacoes"
                        name_tag="Observacoes"
                        value="#{membroComissaoCPManagedBean.currentProposta.observacoes}"/>

                </c:if>

                <br/>

                <h:commandLink
                    id="backbtn"
                    value="Voltar"
                    class="btn btn-primary"
                    action="membro_ccp_index?faces-redirect=true"/>
                &nbsp;
                <c:if test="#{membroComissaoCPManagedBean.currentProposta.estado.nomeTipo == 'Análise'
                              and loginManagedBean.latestConcurso.estadoConcurso.nomeTipo.equalsIgnoreCase(loginManagedBean.ESTADO_CONCURSO_PERIODO_VALIDACAO)}">                
                    <h:commandButton
                        id="aceitar"
                        value="Aceitar"
                        class ="btn btn-primary"
                        action="#{membroComissaoCPManagedBean.aceitarProposta}"/>
                    &nbsp;               
                    <h:commandButton
                        id="rejeitar"
                        value="Rejeitar"
                        class="btn btn-danger"
                        binding="#{membroComissaoCPManagedBean.component}"
                        action="#{membroComissaoCPManagedBean.rejeitarProposta}"/>
                </c:if>

            </em:proposta_details>

            &nbsp;
            <h:messages errorStyle="color: red" />        

        </ui:define>
    </ui:composition>
</html>

dae_project_2017/dae_project_2017-war/web/roles/membro_ccp/membro_ccp_prova_publica_details.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"       
      xmlns:h="http://xmlns.jcp.org/jsf/html"             
      xmlns:em="http://xmlns.jcp.org/jsf/composite/emcomp"            
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">     

    <ui:composition template="../../templates/skeleton.xhtml">

        <ui:define name="title"> 
            Detalhes de Prova Pública
        </ui:define>

        <ui:define name="main" class="form"> 

            <h:form enctype="multipart/form-data">
                <em:input_date 
                    id_tag="data"
                    name_tag="Data"
                    value="#{membroComissaoCPManagedBean.currentProvaPublica.data}"
                    is_required="false"
                    is_disabled="true"
                    />

                <em:input_field 
                    id_tag="local"
                    name_tag="Local"
                    value="#{membroComissaoCPManagedBean.currentProvaPublica.local}"
                    is_required="false"
                    is_disabled="true"
                    />

                <h4 class="form-group text-center"> Membros do Júri </h4>

                <em:input_field 
                    id_tag="juri_mccp"
                    name_tag="Membro CCP"
                    value="#{membroComissaoCPManagedBean.currentProvaPublica.juriMembroCCPNome}"
                    is_required="false"
                    is_disabled="true"
                    />

                <em:input_field 
                    id_tag="juri_orientador"
                    name_tag="Orientador"
                    value="#{membroComissaoCPManagedBean.currentProvaPublica.juriOrientadorNome}"
                    is_required="false"
                    is_disabled="true"
                    />

                <em:input_field 
                    id_tag="juri_professor"
                    name_tag="Professor"
                    value="#{membroComissaoCPManagedBean.currentProvaPublica.juriProfessorNome}"
                    is_required="false"
                    is_disabled="true"
                    />

                <h5 text="text-center">Ata</h5>
                <h6>Para finalizar o trabalho adicione o a Ata da prova pública</h6>

                <div class="form-group">
                    <p:growl id="growlcv" showDetail="true" />
                    <p:fileUpload
                        value="#{uploadManager.file}" 
                        mode="simple" 
                        skinSimple="true"/>

                    <p:commandButton value="Finalizar" 
                                     ajax="false" 
                                     actionListener="#{uploadManager.upload('atas/')}"
                                     action="#{membroComissaoCPManagedBean.adicionarAta()}"/>
                </div>

                <div class="form-group">
                    <h:commandLink
                        value="Voltar"
                        class="btn btn-primary"
                        action="membro_ccp_index?faces-redirect=true"/>
                </div>
            </h:form>

            <h:messages errorStyle="color: red" />

        </ui:define>
    </ui:composition>
</html>

dae_project_2017/dae_project_2017-war/web/roles/membro_ccp/membro_ccp_trabalho_atribuir_professores.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:em="http://xmlns.jcp.org/jsf/composite/emcomp"            
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
     <ui:composition template="../../templates/skeleton.xhtml">

       <ui:define name="title">
            Atribuicao de professores
        </ui:define>

        <ui:define name="main">
            <h:form>
                <div>
                   <h1>Atribuicao de professores</h1>
                </div>
                <div class="item">
                    <em:view_field id_tag="titulo" name_tag="Titulo:" 
                                   value="#{membroComissaoCPManagedBean.currentTrabalho.titulo}"/>
                </div>
                <div class="item">
                    <em:view_field id_tag="resumo" name_tag="Resumo:" 
                                   value="#{membroComissaoCPManagedBean.currentTrabalho.resumo}"/>
                </div>
                <div class="item">
                    <em:view_field id_tag="estudante" name_tag="Estudante:" 
                                   value="#{membroComissaoCPManagedBean.currentTrabalho.estudanteUsername}"/>
                </div>
                <div class="item">
                    <p:outputLabel value="Orientadores:" for="orientadores"/>
                    <h:selectManyCheckbox 
                        id="orientadores" 
                        value="#{membroComissaoCPManagedBean.currentTrabalho.professorUsernames}">
                        <c:forEach items="#{membroComissaoCPManagedBean.allProfessores}" var="professor" > 
                            <f:selectItem itemValue="#{professor.username}" itemLabel="#{professor.nome}" />
                        </c:forEach>   
                    </h:selectManyCheckbox>
                    <h:message for="orientadores" errorStyle="color: red" />
                </div>
                
                <c:if test="#{membroComissaoCPManagedBean.currentTrabalho.tipoProponente.nomeTipo == 'Instituicao'}">
                    <div class="item">
                        <p:outputLabel value="Supervisor:" for="supervisors"/>
                        <h:selectOneMenu 
                            id="supervisors" 
                            value="#{membroComissaoCPManagedBean.currentTrabalho.supervisorEmail}">
                            <c:forEach items="#{membroComissaoCPManagedBean.allSupervisorsOfInstituicao}" var="supervisor" > 
                                    <f:selectItem itemValue="#{supervisor.email}" itemLabel="#{supervisor.nome}" />
                            </c:forEach>   
                        </h:selectOneMenu>
                        <h:message for="supervisors" errorStyle="color: red" />
                    </div>
                </c:if>
                <h:link value="Voltar" 
                    outcome="membro_ccp_index?faces-redirect=true"
                    class="btn btn-danger" 
                    />
                &nbsp;
                <h:commandButton
                    id="submit"
                    value="Update"
                    class="btn btn-primary" 
                    binding="#{membroComissaoCPManagedBean.component}"
                    action="#{membroComissaoCPManagedBean.updateTrabalhoOrientadores()}" />
                <h:message for="submit" style="color: red"/>
                
            </h:form>
        </ui:define>
     </ui:composition>
</html>