dae_project_2017/dae_project_2017-war/src/java/web/ManageBeans/LoginManagedBean.java
package web.ManageBeans;

import dtos.ConcursoDTO;
import ejbs.ConcursoBean;
import entities.roles.UserGroup;
import javax.faces.bean.SessionScoped;
import java.io.Serializable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.ws.rs.client.Client;
import javax.ws.rs.client.ClientBuilder;
import javax.ws.rs.core.GenericType;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import util.URILookup;
import utils.embeddable.EstadoConcurso;
import web.FacesExceptionHandler;

@ManagedBean
@SessionScoped
public class LoginManagedBean implements Serializable {

    private String username;
    private String password;
    
    private static final Logger logger = Logger.getLogger("web.UserManagedBean");
    
    public LoginManagedBean() {
        
    }
    
    public String redirect() {
        if (isUserInRole(UserGroup.GROUP.Estudante)) {
            return "/roles/estudante/estudante_index?faces-redirect=true";
        }
        
        if (isUserInRole(UserGroup.GROUP.Proponente)) {
            return "/roles/proponente/proponente_index?faces-redirect=true";
        }
        
        if (isUserInRole(UserGroup.GROUP.MembroCCP)) {
            return "/roles/membro_ccp/membro_ccp_index?faces-redirect=true";
        }
        
        return "error403?faces-redirect=true";
    }

    public String login() {
        FacesContext context = FacesContext.getCurrentInstance();
        HttpServletRequest request
                = (HttpServletRequest) context.getExternalContext().getRequest();
        try {
            request.login(username, password);
        } catch (ServletException e) {
            logger.log(Level.WARNING, e.getMessage());
            return "error401?faces-redirect=true";
        }
        
        return redirect();
    }

    public boolean isUserInRole(UserGroup.GROUP group) {
        return isUserInRole(group.toString());
    }
    
    public boolean isUserInRole(String role) {
        return (isSomeUserAuthenticated() && FacesContext.getCurrentInstance().getExternalContext().isUserInRole(role));
    }

    public boolean isSomeUserAuthenticated() {
        return FacesContext.getCurrentInstance().getExternalContext().getUserPrincipal() != null;
    }

    public String logout() {
        //https://issues.jboss.org/browse/WELD-2123
        //https://stackoverflow.com/questions/26822225/glassfish-4-1-bug-session-invalidate-nullpointer-exception
        FacesContext context = FacesContext.getCurrentInstance();
        // remove data from beans:
        for (String bean : context.getExternalContext().getSessionMap().keySet()) {
            context.getExternalContext().getSessionMap().remove(bean);
        }
        // destroy session:
       FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
        // using faces-redirect to initiate a new request:
        return "/login.xhtml?faces-redirect=true";
    }

    public String clearLogin() {
        if (isSomeUserAuthenticated()) {
            logout();
        }
        return "login.xhtml?faces-redirect=true";
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    
    // #######################################################################
    // CONCURSOS
    // #######################################################################

    public String getESTADO_CONCURSO_PERIODO_MARCACAO_PROVA_PUBLICA() {
        return EstadoConcurso.PERIODO_MARCACAO_PROVAS_PUBLICAS.getNomeTipo();
    }

    public String getESTADO_CONCURSO_PERIODO_ENTREGA_TRABALHOS() {
        return EstadoConcurso.PERIODO_ENTREGA_TRABALHOS.getNomeTipo();
    }

    public String getESTADO_CONCURSO_PERIODO_SERIACAO() {
        return EstadoConcurso.PERIODO_SERIACAO.getNomeTipo();
    }
    
    public String getESTADO_CONCURSO_PERIODO_CANDIDATURAS() {
        return EstadoConcurso.PERIODO_CANDIDATURAS.getNomeTipo();
    }
    
    public String getESTADO_CONCURSO_PERIODO_VALIDACAO() {
        return EstadoConcurso.PERIODO_VALIDACAO.getNomeTipo();
    }
    
    public String getESTADO_CONCURSO_PERIODO_PROPOSTAS() {
        return EstadoConcurso.PERIODO_PROPOSTAS.getNomeTipo();
    }
    
    public ConcursoDTO getLatestConcurso() {
        ConcursoDTO latestConcurso = null;
        
        Client client = ClientBuilder.newClient();
        Response response = client.target(URILookup.getBaseAPI())
                .path(ConcursoBean.REST_PATH_GET_LATEST_CONCURSO)
                .request(MediaType.APPLICATION_XML)
                .get();
        
        if (response.getStatusInfo().getFamily() != Response.Status.Family.SUCCESSFUL) {
            logger.warning("Erro ao carregar o concurso");            
        }
        
        return response.readEntity(new GenericType<ConcursoDTO>(){});
    }
}

dae_project_2017/dae_project_2017-war/src/java/web/ManageBeans/PublicoManagedBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package web.ManageBeans;

import dtos.TrabalhoDTO;
import ejbs.TrabalhoBean;
import javax.faces.component.UIComponent;
import web.FacesExceptionHandler;
import java.io.Serializable;
import java.util.Collection;
import java.util.List;
import java.util.logging.Logger;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.ws.rs.client.Client;
import javax.ws.rs.client.ClientBuilder;
import javax.ws.rs.core.GenericType;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import util.URILookup;

@ManagedBean
@SessionScoped
public class PublicoManagedBean implements Serializable {

    private UIComponent component;

    private TrabalhoDTO currentTrabalho;
    private Client client; 
    
    private static final Logger logger = Logger.getLogger("web.Public");

    // ####################################################
    public PublicoManagedBean() {
        currentTrabalho = new TrabalhoDTO();
        client = ClientBuilder.newClient();
    }

    
    //#########################################################
//                                      TRABALHOS
    //########################################################

    public Collection<TrabalhoDTO> getAllTrabalhosFinalizados() {
        Response response = client.target(URILookup.getBaseAPI())
                .path(TrabalhoBean.REST_PATH_GET_ALL_FINALIZADOS)
                .request(MediaType.APPLICATION_XML)
                .get();
        if (response.getStatusInfo().getFamily() != Response.Status.Family.SUCCESSFUL) {
            FacesExceptionHandler.handleException(
                    response,
                    "Erro ao carregar os trabalhos",
                    component, logger
            );
        }
        return response.readEntity(new GenericType<List<TrabalhoDTO>>() {});
    }
    
    
    public UIComponent getComponent() {
        return component;
    }

    public void setComponent(UIComponent component) {
        this.component = component;
    }

    public TrabalhoDTO getCurrentTrabalho() {
        return currentTrabalho;
    }

    public void setCurrentTrabalho(TrabalhoDTO currentTrabalho) {
        this.currentTrabalho = currentTrabalho;
    }

}

dae_project_2017/dae_project_2017-war/web/download_file.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui" >
    <h:head>
        <f:metadata>
            <f:viewParam name="trabalhoid" value="#{downloadManager.trabalhoId}" required="true"/>
            <f:viewParam name="documentonome" value="#{downloadManager.documentoNome}" required="true"/>
        </f:metadata>
    </h:head>

    <h:body>
        <h2 style="text-align: center">Descarregar ficheiro #{downloadManager.documentoNome}</h2>

        
            <h4 style="text-align: center"> 
                <h:form >
                    <div class="form-group">
                        <h:commandButton id="download" value="Download" class="btn btn-primary">
                            <p:fileDownload value="#{downloadManager.getFile()}" />
                        </h:commandButton>
                        <h:message for="download" class="help-block" errorStyle="color: red" />
                    </div>
                </h:form>

            </h4>

    </h:body>
</html>

dae_project_2017/dae_project_2017-war/web/error401.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"       
      xmlns:h="http://xmlns.jcp.org/jsf/html"                                 
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">      

    <ui:composition template="/templates/skeleton.xhtml">

        <ui:define name="title">
            401 - Unauthorized
        </ui:define>

        <ui:define name="main">
            <h3 class="text-center">Check again your <b>username</b> and/or <b>password</b></h3>
            <h:form>
                <div class="text-center">
                    <h:commandLink value="Voltar" class="btn btn-primary"  action="#{loginManagedBean.clearLogin}"/>
                </div>
            </h:form>
        </ui:define>
    </ui:composition>
</html> 

dae_project_2017/dae_project_2017-war/web/error403.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"       
      xmlns:h="http://xmlns.jcp.org/jsf/html"                                 
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">      

    <ui:composition template="/templates/skeleton.xhtml">

        <ui:define name="title">
            403 - Forbidden
        </ui:define>

        <ui:define name="main">
            <h3 class="text-center">Check again your <b>username</b> and/or <b>password</b></h3>
            <h:form>
                <div class="text-center">
                    <h:commandLink value="Voltar" class="btn btn-primary"  action="#{loginManagedBean.clearLogin}"/>
                </div>
            </h:form>
        </ui:define>
    </ui:composition>
</html> 

dae_project_2017/dae_project_2017-war/web/login.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"       
      xmlns:h="http://xmlns.jcp.org/jsf/html"       
      xmlns:f="http://java.sun.com/jsf/core"       
      xmlns:p="http://primefaces.org/ui"       
      xmlns:em="http://xmlns.jcp.org/jsf/composite/emcomp"            
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">      

    <ui:composition template="/templates/skeleton.xhtml">

        <ui:define name="title">
            DAE 2017
        </ui:define>

        <ui:define name="main">
            <div>
                <c:if test="${not loginManagedBean.someUserAuthenticated}">
                    <h:form rendered="${not loginManagedBean.someUserAuthenticated}">

                        <em:input_field
                            id_tag="username"
                            name_tag="Username"
                            value="#{loginManagedBean.username}"/>

                        <em:input_pass
                            id_tag="password"
                            name_tag="Password"
                            value="#{loginManagedBean.password}"/>

                        <div class="form-group">
                            <h:commandButton value="Login" action="#{loginManagedBean.login}" />
                        </div>

                    </h:form>
                </c:if>
                <c:if test="${loginManagedBean.someUserAuthenticated}">
                    <p>You are logged in!</p>
                    <h:link outcome="${loginManagedBean.redirect()}" value="Return to Home Page"/>
                </c:if>
            </div>
            
            <hr/>
            
            <em:dt 
                title="Trabalhos Finalizados"
                id="trabalhos_finalizados"
                headers="#{['Titulo Trabalho', 'Tipo de Trabalho', 'Resumo']}" 
                props="#{['titulo','tipoTrabalho','resumo']}" 
                list="#{publicoManagedBean.allTrabalhosFinalizados}">

                <p:column headerText="Ações">     
                    <h:form>
                        <h:commandLink value="Detalhes" action="trabalho_finalizado_detalhes?faces-redirect=true" >
                            <f:setPropertyActionListener target="#{publicoManagedBean.currentTrabalho}" value="#{object}"/>
                        </h:commandLink>
                    </h:form>
                </p:column> 
            </em:dt>

        </ui:define>
    </ui:composition>

</html> 

dae_project_2017/dae_project_2017-war/web/trabalho_finalizado_detalhes.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"       
      xmlns:h="http://xmlns.jcp.org/jsf/html"                     
      xmlns:em="http://xmlns.jcp.org/jsf/composite/emcomp"            
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:p="http://primefaces.org/ui">      

    <ui:composition template="/templates/skeleton.xhtml">

        <ui:define name="title">
            Detalhes do Trabalho
        </ui:define>

        <ui:define name="main">
            
            <h:form>

                <em:input_field
                    id_tag="titulo" 
                    name_tag="Titulo"
                    value="#{publicoManagedBean.currentTrabalho.titulo}"
                    is_disabled="true"
                    is_required="false"/>
                
                <em:input_field
                    id_tag="resumo" 
                    name_tag="Resumo"
                    value="#{publicoManagedBean.currentTrabalho.resumo}"
                    is_disabled="true"
                    is_required="false"/>

                <em:input_field
                    id_tag="tipo_trabalho" 
                    name_tag="Tipo de Trabalho"
                    value="#{publicoManagedBean.currentTrabalho.tipoTrabalho.nomeTipo}"
                    is_disabled="true"
                    is_required="false"/>

                <c:if test="#{publicoManagedBean.currentTrabalho.tipoTrabalho.nomeTipo == 'Estágio'}">
                    <em:input_field
                        id_tag="local_realizacao"  
                        name_tag="Local Realizacao"
                        value="#{publicoManagedBean.currentTrabalho.proposta.localRealizacao != null ? 
                                 publicoManagedBean.currentTrabalho.proposta.localRealizacao : 'Por definir'}"
                        is_disabled="true"
                        is_required="false"/>
                </c:if>

                <em:input_field
                    id_tag="plano" 
                    name_tag="Plano De Trabalho"
                    value="#{publicoManagedBean.currentTrabalho.proposta.planoTrabalho}"
                    is_disabled="true"
                    is_required="false"/>

                <em:view_string_list 
                    name_tag="Professores"
                    list="#{publicoManagedBean.currentTrabalho.professorUsernames}"
                    empty_value_override="Ainda nao foram alocados professores para este trabalho"/>         

                <em:view_string_list 
                    name_tag="Areas Cientificas:"
                    list="#{publicoManagedBean.currentTrabalho.proposta.areasCientificas}"/>    


                <em:view_string_list 
                    name_tag="Objetivos:"
                    list="#{publicoManagedBean.currentTrabalho.proposta.objectivos}"/>


                <em:view_string_list 
                    name_tag="Requisitos:"
                    list="#{publicoManagedBean.currentTrabalho.proposta.requisitosTrabalho}"/>


                <em:view_string_list 
                    name_tag="Apoios:"
                    list="#{publicoManagedBean.currentTrabalho.proposta.apoios}"/>

                <div class="form-group">
                    <p:outputLabel value="Bibliografia"/>
                    <ul>
                        <c:forEach items="${publicoManagedBean.currentTrabalho.proposta.bibliografia}" var="area">
                            <li>
                                <span>${area.titulo},&nbsp;${area.autor}</span>
                            </li>
                        </c:forEach>

                        <c:if test="#{publicoManagedBean.currentTrabalho.proposta.bibliografia.size() == 0}">  
                            <li>"Sem bibliografia disponivel"</li>
                        </c:if>  
                    </ul>
                </div>
                    
                <div class="form-group">
                    <em:dt 
                        title="Artefactos publicos"
                        id="documentos"
                        headers="#{['Nome', 'Tipo', 'Data']}" 
                        props="#{['nome','mimeType','uploadedAt']}" 
                        list="#{publicoManagedBean.currentTrabalho.artefactosPublicos}">

                        <p:column headerText="Acções">     
                            <h:form>
                                <p:commandButton value="Download" ajax="false">
                                    <p:fileDownload value="#{downloadManager.getFile(object)}" />
                                </p:commandButton>
                            </h:form>
                        </p:column> 

                    </em:dt>
                </div>
    
                <div class="form-group">
                    <h:link value="Voltar" 
                            outcome="login"
                            class="btn btn-primary" 
                            />
                </div>
            </h:form>
        </ui:define>
    </ui:composition>

</html> 